In [2]:
import numpy as np

data = np.random.randn(2, 3)
data

array([[-0.08966761,  0.52108022,  0.18202069],
       [-1.96383387, -0.09940177,  1.33226475]])

In [3]:
data.shape
data.dtype

dtype('float64')

In [ ]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

In [4]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr
arr * arr
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arr = np.arange(10)
arr
arr[5]
arr[5:8]
arr[5:8] = 12
arr

In [ ]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
names
data

In [ ]:
names != 'Bob'
data[~(names == 'Bob')]

In [10]:
arr = np.arange(15).reshape((3, 5))
arr
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [15]:
arr = np.arange(15).reshape((3, 5))
arr.swapaxes(0, 1)

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [16]:
arr = np.random.randn(5, 4)
arr
arr.mean()
np.mean(arr)
arr.sum()

-5.626690698854368

In [17]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28], dtype=int32)

In [18]:
arr = np.random.randn(100)
(arr > 0).sum() 

62

In [19]:
arr = np.random.randn(6)
arr
arr.sort()
arr

array([-0.92594893, -0.44493517, -0.14036362,  0.85513675,  1.2192732 ,
        1.97728369])